TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devilm200.db
DATA += devilm200.proto

#=======================================
include $(TOP)/configure/RULES
